# This file will be used to configure the project
Hacker: true
name: steve
hobbies:
- skateboarding
- snowboarding
- go
clothing:
  jacket: leather
  trousers: denim
age: 35
eyes : brown
<<<<<<< HEAD
beard: true
=======
beard: true
>>>>>>> 8a15e5ae0190388eda04ecd97c83cddbb055456b
