/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
module interpreter_types;

import thrift.base;
import thrift.codegen.base;
import thrift.util.hashset;

