/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
module Language;

import thrift.base;
import thrift.codegen.base;
import thrift.util.hashset;

import interpreter_types;

interface Language {
  string Interprete(string code);

  enum methodMeta = [
    TMethodMeta(`Interprete`, 
      [TParamMeta(`code`, 1)]
    )
  ];
}
