apiVersion: v1
kind: Service
metadata:
  name: car-insurance
  labels:
    app: car-insurance
spec:
  type: LoadBalancer
  ports:
    # the port that this service should serve on
  - port: 80
    targetPort: 8080
  selector:
    app: car-insurance
