name: Default
schema:
  - name: Name
    type: string
  - name: Age
    type: number
  - name: Gender
    type: string
rules:
  - id: 0
    when: example 1
    then: example 1

  - id: 1
    when: example 2
    then: example 2

  - id: 2
    when: example 3
    then: example 3

  - id: 3
    when: example 4
    then: example 4