apiVersion: v1
kind: ReplicationController
metadata:
  name: server
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
      - name: langserver
        image: michaelgolfi/langserver
        ports:
        - containerPort: 9090
      - name: server
        image: michaelgolfi/server
        ports:
        - containerPort: 8080
        env:
        - name: RULES_BASE_URI
          value: http://127.0.0.1:9090/api/v1/rules