kind: Service
apiVersion: v1
metadata:
  name: rules-frontend
  labels:
    app: rules-frontend
spec:
  type: NodePort
  ports:
  - port: 80
    protocol: TCP
    name: http
    nodePort: 30010
  selector:
    component: rules-frontend
