apiVersion: v1
kind: ReplicationController
metadata:
  name: car-insurance
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: car-insurance
    spec:
      containers:
      - name: car-insurance
        image: michaelgolfi/car_insurance
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 8080
